name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm i

      - name: Build with Rollup
        run: npm run build

      - name: Deploy
        run: |
          sftp put -r ./dist/* /var/www/code-workshop-kit.com/test-html -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i ${{ secrets.SSH_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_ADDRESS }}
