name: Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy through SSH + git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_ADDRESS }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: cd /var/www/code-workshop-kit.com/html && git pull
