name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm i

      - name: Build with Rollup
        run: npm run build

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.SSH_ADDRESS }}
          username: ${{ secrets.SSH_USER }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: './dist/*'
          remote_path: '/var/www/code-workshop-kit.com/html'
          args: '-o ConnectTimeout=5'